### ISSUE TITLE
Error while  fetching data for a specific date

### ISSUE THREAD

**Issue by 2020-abhilash** [techyaura/nse-bhavcopy#6]
`$ node index.js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at Request.onRequestError (E:\projects\stock-analysis\get_data\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by 2020-abhilash** [comment]
Below is the code
`const BhavCopy = require("nse-bhavcopy");
const request = new BhavCopy({});

request.download({
    month: "DEC",
    year: 2019,
    day: 07
}).then(data => {
    console.log(data);
}).catch(err => {
    console.log(err);
});
`

**Comment by techyaura** [comment]
@2020-abhilash 

I don't think so, it is related to the module. Just check your local configuration for node.
